from start import models

def populate():
    # Populate GamingCompany Table
    microsoft = models.GamingCompany.objects.create(name="Microsoft")
    sony = models.GamingCompany.objects.create(name="Sony")
    nintendo = models.GamingCompany.objects.create(name="Nintendo")

    # Populate Console Table
    nes = models.Console.objects.create(name="NES",generation=0,company=nintendo)
    super_nes = models.Console.objects.create(name="Super NES",generation=1,company=nintendo)
    n64 = models.Console.objects.create(name="Nintendo 64",generation=2,company=nintendo)
    gamecube = models.Console.objects.create(name="Gamecube",generation=3,company=nintendo)
    wii = models.Console.objects.create(name="Wii",generation=4,company=nintendo)
    wii_u = models.Console.objects.create(name="Wii U",generation=5,company=nintendo)
    switch = models.Console.objects.create(name="Switch",generation=6,company=nintendo)

    playstation = models.Console.objects.create(name="Playstation",generation=2,company=sony)
    playstation2 = models.Console.objects.create(name="Playstation 2",generation=3,company=sony)
    playstation3 = models.Console.objects.create(name="Playstation 3",generation=4,company=sony)
    playstation4 = models.Console.objects.create(name="Playstation 4",generation=5,company=sony)
    playstation5 = models.Console.objects.create(name="Playstation 5",generation=6,company=sony)

    xbox = models.Console.objects.create(name="Xbox",generation=3,company=microsoft)
    xbox360 = models.Console.objects.create(name="Xbox 360",generation=4,company=microsoft)
    xbox1 = models.Console.objects.create(name="Xbox One",generation=5,company=microsoft)
    xboxX = models.Console.objects.create(name="Xbox X",generation=6,company=microsoft)

    # Populate the Game Table
    zeldaBreath = models.Game.objects.create(name="Zelda: Breath of the Wild")
    zeldaBreath.consoles.add(switch)
    zeldaBreath.save()
    zeldaTwilight = models.Game.objects.create(name="Zelda: Twilight Princess")
    zeldaTwilight.consoles.add(wii,wii_u)
    zeldaTwilight.save()
    zeldaOcarina = models.Game.objects.create(name="Zelda: Ocarina of Time")
    zeldaOcarina.consoles.add(n64)
    zeldaOcarina.save()
    zeldaMajora = models.Game.objects.create(name="Zelda: Majora's Mask")
    zeldaMajora.consoles.add(n64)
    zeldaMajora.save()
    zeldaLink = models.Game.objects.create(name="Zelda: Link to the Past")
    zeldaLink.consoles.add(super_nes)
    zeldaLink.save()
    zelda = models.Game.objects.create(name="The Legend of Zelda")
    zelda.consoles.add(nes,super_nes)
    zelda.save()
    super_mario = models.Game.objects.create(name="Super Mario Bros")
    super_mario.consoles.add(super_nes)
    super_mario.save()
    doom2016 = models.Game.objects.create(name="Doom 2016")
    doom2016.consoles.add(switch,playstation4,xbox1)
    doom2016.save()
    fortnite = models.Game.objects.create(name="Fortnite")
    fortnite.consoles.add(switch,playstation4,xbox1)
    fortnite.save()
    godofwar = models.Game.objects.create(name="God of War 2018")
    godofwar.consoles.add(playstation4)
    godofwar.save()
    halo4 = models.Game.objects.create(name="Halo 4")
    halo4.consoles.add(xbox360)
    halo4.save()
    halo5 = models.Game.objects.create(name="Halo 5")
    halo5.consoles.add(xbox1)
    halo5.save()

    # Populate the Player table
    jimmy = models.Player.objects.create(name="Jimmy",fav_console=switch)
    jimmy.games.add(zeldaBreath,zeldaOcarina,fortnite)
    jimmy.save()
    john = models.Player.objects.create(name="John",fav_console=playstation4)
    john.games.add(doom2016,godofwar,fortnite)
    john.save()
    ninja = models.Player.objects.create(name="Ninja",fav_console=xbox1)
    ninja.games.add(fortnite)
    ninja.save()
    joe = models.Player.objects.create(name="Joe",fav_console=n64)
    joe.games.add(zeldaOcarina,zeldaMajora)
    joe.save()
