# Generated by Django 3.0.3 on 2020-03-31 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('generation', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('consoles', models.ManyToManyField(to='start.Console')),
            ],
        ),
        migrations.CreateModel(
            name='GamingCompany',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fav_console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Console')),
                ('games', models.ManyToManyField(to='start.Game')),
            ],
        ),
        migrations.AddField(
            model_name='console',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.GamingCompany'),
        ),
    ]
